[package]
name = "shoal-core"
version.workspace = true
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dirs = "6.0.0"
saphyr = "0.0.6"
serde = "1.0.228"
serde-saphyr = "0.0.10"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
